/* Escola do Ás — explicações completas (Nível 5). Formato em content-qx0.js. */
(function (g) {
  'use strict';
  const C = g.Curriculum, X = (C.QX = C.QX || {});
  const q = (k, e, w) => (X[k] = [e, w]);
  // el · Pensamento de elite
  q('el_1#0', 'A ordem é reconhecimento (o que é esta situação), diagnóstico (o que ela significa) e execução (o que fazer).', ['Executar antes de reconhecer é agir sem entender.', null, 'Diagnosticar exige primeiro reconhecer a situação.', 'Há ordem, e ela importa.']);
  q('el_1#1', 'O treino de elite transforma conhecimento explícito em reconhecimento automático: você vê o padrão e já sabe o que ele pede.', ['Decorar mais não cria reconhecimento.', null, 'Jogar rápido sem pensar é impulsividade.', 'Usar solver na mesa é proibido.']);
  q('el_2#0', 'Quando o adversário percebe e se ajusta, reajuste: o jogo é uma conversa, e a melhor resposta muda.', ['Insistir na exploração depois do ajuste faz você ser explorado.', null, 'Sair da mesa é exagero.', 'Blefar mais é a resposta errada a quem passou a pagar.']);
  q('el_2#1', 'Com poucas observações, a crença deve mudar pouco: pode ser acaso.', ['Mudar muito com pouca evidência é reagir a ruído.', null, 'Mudar nada ignora a informação.', 'Totalmente é ainda pior.']);
  q('el_3#0', 'Contra adaptação baixa, mantenha a exploração por mais tempo: ele não percebe.', ['Nunca explorar desperdiça o erro dele.', null, 'Mudar a cada mão é desnecessário contra quem não se adapta.', 'Sair da mesa abandona um bom alvo.']);
  q('el_3#1', 'Contra quem tem tilt fácil, depois de perder um pote grande, espere mais agressão e mais blefes.', ['Mais cuidado é o oposto do tilt.', null, 'Desistir mais também é o oposto.', 'Há um padrão previsível.']);
  q('el_4#0', 'Planejar as ruas seguintes evita decisões soltas e ranges incoerentes: cada decisão conversa com a próxima.', ['O plano não evita ganhar potes.', null, 'Blefes continuam no plano.', 'Apostas pequenas continuam possíveis.']);
  q('el_4#1', 'Antes do turn, pergunte "quais rivers quero ver?": o plano olha para frente.', ['O que já ganhou não muda a decisão.', null, 'Quem está olhando não importa.', 'O rake não entra no plano.']);
  q('el_5#0', 'Você entendeu um princípio quando consegue criar um exemplo novo que o obedeça: é a generalização.', ['Ler a solução não prova entendimento.', null, 'Decorar a frase não prova que você sabe aplicar.', 'Acertar uma vez pode ser sorte.']);
  q('el_5#1', 'Abstração agrupa situações pelas características que importam para a estratégia: textura, vantagem de nuts, SPR.', ['Aparência engana.', null, 'Naipes sozinhos não definem a estratégia.', 'Sorte não agrupa nada.']);
  q('el_6#0', 'Meça o EV perdido porque os erros têm custos muito diferentes: o dinheiro está no custo, não na contagem.', ['Não é mais fácil; é mais útil.', null, 'Acertos importam, mas não medem o custo dos erros.', 'O app não exige: é método.']);
  q('el_6#1', 'River de um pote com 3-bet é situação de alto peso: pote grande, decisão cara.', ['Desistir de 7-2 no UTG é decisão barata e óbvia.', null, 'Pagar o small blind é barato.', 'Limp é decisão pequena.']);
  q('el!ex#0', 'K-7-2, Q-6-2 e J-8-3 de naipes diferentes têm uma carta alta e duas baixas, sem conexão: mesmo princípio, mesma estratégia (c-bet pequena e frequente).', ['As três têm naipes diferentes.', null, 'Nenhuma é pareada.', 'Não são conectadas.']);
  q('el!ex#1', 'Se você explorava as desistências no turn e ele passou a pagar mais, reajuste: menos blefes e mais valor fino.', ['Blefar mais contra quem paga mais perde fichas.', null, 'Parar de apostar perde o valor.', 'Sair da mesa é exagero.']);
  q('el!ex#2', '2,5 ÷ 0,02 = 125. Um erro de 2,5 bb vale 125 erros de 0,02 bb.', ['12,5 erra a divisão por 10.', null, '1.250 erra por 10 para mais.', '2,5 é o próprio erro maior.']);
  // hu · Heads-up
  q('hu_1#0', 'No heads-up com 100 bb, o botão abre de 80% a 90% das mãos: contra um só adversário, quase todas têm valor.', ['20% a 30% é a abertura de uma mesa cheia.', '50% é apertado demais para o heads-up.', null, '100% inclui as piores mãos, que perdem valor.']);
  q('hu_1#1', 'K2 de naipes diferentes contra uma mão aleatória tem cerca de 50%: é uma "moeda". Por isso mãos assim são jogáveis no heads-up.', ['30% subestima: o rei sozinho já vale muito contra mãos aleatórias.', null, '70% é de mãos bem mais fortes.', '10% é absurdo.']);
  q('hu_2#0', 'O range de limp no heads-up precisa de mãos fortes também; senão o big blind aumenta sempre contra os seus limps.', ['Só mãos fracas deixa o limp fácil de explorar.', null, 'Stacks fundos não são exigência.', 'Precisa de equilíbrio.']);
  q('hu_2#1', 'Com stacks curtos, o limp aparece mais: protege contra o all-in do big blind e arma mãos fortes.', ['Não some; aumenta.', null, 'Não é proibido.', 'Muda: cresce.']);
  q('hu_3#0', 'No heads-up o valor fica mais fino: mãos médias ganham de muitos ranges largos.', ['Mais grosso seria jogar só mãos fortes.', null, 'Muda: fica mais fino.', 'Não há proibição.']);
  q('hu_3#1', 'Contra aberturas largas, o big blind dá 3-bet com frequência alta no heads-up: entre 15% e 25%.', ['Quase zero deixa o botão abrir de graça.', null, 'Igual a 6-max é baixo para o heads-up.', '50% é exagerado.']);
  q('hu_4#0', 'Ajuste um eixo por vez: assim você sabe o que funcionou.', ['Mudando tudo, você não sabe o que deu certo.', null, 'Três ao mesmo tempo confundem a leitura.', 'Sem ajuste, você não explora.']);
  q('hu_4#1', 'Quando perder a leitura, volte à estratégia base: ela não pode ser explorada.', ['Blefar mais sem leitura é chute.', null, 'Desistir de tudo entrega os potes.', 'Acordo não resolve a leitura.']);
  q('hu_5#0', 'No mano a mano de torneio, o valor é linear: a matemática é a conta em fichas.', ['O ICM, aqui, é igual à conta em fichas.', null, 'Não é aleatória.', 'Push/fold é só para stacks curtos.']);
  q('hu_5#1', 'O 2º prêmio ($600) é garantido; a diferença ($400) está em disputa. 50% dela: $200. Total: $800.', ['$600 é só o garantido.', null, '$1.000 é o 1º prêmio.', '$700 aplica a fatia de forma errada.']);
  q('hu!ex#0', 'Com 100 bb no heads-up o botão abre 80% a 90%: Q4o está dentro. Desistir é um erro.', ['O botão abre quase tudo no heads-up.', null, 'Não é indiferente: perde valor.', 'Nada obriga a desistir.']);
  q('hu!ex#1', '$1.000 garantidos (2º prêmio) + 30% de $1.000 (a diferença) = $1.300.', ['$1.000 é só o garantido.', null, '$1.500 seria com 50%.', '$600 não corresponde à conta.']);
  q('hu!ex#2', 'Se você só dá limp com mãos fracas, o big blind deve aumentar contra os seus limps: o limp ficou fácil de ler.', ['Pagar sempre desperdiça a fraqueza.', null, 'Desistir não se aplica: não há aposta.', 'Passar deixa você ver o flop barato.']);
  // lv · Jogo ao vivo
  q('lv_1#0', 'Nos limites baixos ao vivo, os jogadores costumam ser mais passivos e pagar mais antes do flop.', ['Mais agressivos não é o padrão ao vivo nos limites baixos.', null, 'Muito apertados não é o padrão.', 'Não são iguais aos online.']);
  q('lv_1#1', 'Aberturas maiores funcionam ao vivo porque os jogadores pagam mesmo assim: mais valor com mãos fortes.', ['Não há regra da casa sobre isso.', null, 'O rake não é o motivo.', 'Funcionam, por esse motivo.']);
  q('lv_2#0', 'Interprete um sinal comparando com a linha de base da pessoa: cada uma é diferente.', ['Listas genéricas falham com pessoas diferentes.', null, 'Ignorar sempre desperdiça informação.', 'O que os outros dizem não é a linha de base dela.']);
  q('lv_2#1', 'Sinais devem mudar só decisões próximas do limite: são desempate, não base.', ['Mudar todas as decisões por sinais é confiar demais neles.', null, 'Ignorá-los desperdiça informação nas decisões apertadas.', 'Valem em qualquer rua, como desempate.']);
  q('lv_3#0', 'Uma única ficha grande sem declaração vale como pagamento. Para aumentar, declare.', ['Para valer aumento, é preciso declarar.', null, 'Colocar ficha não é desistir.', 'All-in também precisa de declaração.']);
  q('lv_3#1', 'O que você declara em voz alta é obrigatório: palavra dada vale.', ['Não pode ser mudado.', null, 'Vale.', 'Vale em qualquer rua.']);
  q('lv_4#0', 'Depois de mostrar blefes, a sua imagem é de quem blefa: aposte mais por valor e blefe menos.', ['Blefar mais com imagem de blefador perde fichas.', null, 'Parar de jogar desperdiça a imagem.', 'Mudar de mesa desperdiça a imagem.']);
  q('lv_4#1', 'Na conversa de mesa, evite revelar o seu raciocínio: informação é fichas.', ['Ser simpático é ótimo.', null, 'Cumprimentar é educação.', 'Falar não é problema; revelar o raciocínio é.']);
  q('lv_5#0', 'Estruturas ao vivo costumam ser mais lentas e fundas: mais jogo depois do flop.', ['Mais rápidas e curtas é o padrão online.', null, 'Não são iguais às online.', 'Push/fold é só para stacks curtos.']);
  q('lv_5#1', 'O rake ao vivo nos limites baixos pesa muito: escolha bem o limite.', ['É muito relevante.', null, 'Existe.', 'Costuma ser maior, proporcionalmente.']);
  q('lv!ex#0', 'Se o range dele é quase só valor, siga o range: um sinal só desempata decisões próximas do limite.', ['Pagar pelo sinal contra um range de valor perde fichas.', null, 'Aumentar contra valor é pior ainda.', 'Perguntar não é decisão.']);
  q('lv!ex#1', 'Você disse "pago": vale o pagamento. O que se declara em voz alta vale.', ['O aumento não foi declarado.', null, 'Vale o que foi dito.', 'O dealer aplica a regra: vale o que você disse.']);
  q('lv!ex#2', 'Se a mesa paga todas as aberturas de 3 bb, abra QQ para cerca de 5 a 6 bb: eles pagam mesmo assim, e você ganha mais valor.', ['2 bb deixa valor na mesa.', '3 bb é o que eles pagam sempre: dá para cobrar mais.', null, 'Limp com QQ desperdiça uma mão forte.']);
  // hc · Competição em alto nível
  q('hc_1#0', 'Nas semanas antes do evento, foque nas situações do formato do evento (stacks, estrutura, ICM): prepare o que vai acontecer.', ['Estudar qualquer coisa dispersa a preparação.', null, 'Só cash ignora o formato do evento.', 'Sem preparação, você chega frio.']);
  q('hc_1#1', 'Os eventos principais das séries atraem muitos recreativos: são o sonho de muita gente, e isso torna o field mais fraco.', ['Não são só profissionais.', null, 'Costumam ter muitos jogadores.', 'Têm muitos recreativos.']);
  q('hc_2#0', 'Entre os dias de torneio, a prioridade é recuperação e sono: o próximo dia decide.', ['Comemorar à custa de sono custa caro no dia seguinte.', null, 'Jogar cash cansa mais.', 'Revisar a noite toda tira o sono.']);
  q('hc_2#1', 'Antes do próximo dia, revise stack, estrutura e os adversários da sua mesa: curto e útil.', ['Sem revisão você começa às cegas.', null, 'Todas as mãos do dia tomam tempo demais.', 'Outros torneios não ajudam agora.']);
  q('hc_3#0', 'Numa mesa final transmitida, as cartas são mostradas com atraso, para proteger o jogo.', ['Ao vivo, sem atraso, quem assiste poderia passar informação.', null, 'Elas são mostradas, mas com atraso.', 'Não é só no fim: com atraso, durante a transmissão.']);
  q('hc_3#1', 'Sob pressão, apoie-se na rotina e no que foi treinado: o automático treinado aguenta a pressão.', ['O instinto do momento é o que a pressão distorce.', null, 'A plateia não decide nada.', 'Sorte não é critério de decisão.']);
  q('hc_4#0', 'Numa entrevista durante o evento, evite revelar leituras e estratégias: os adversários estão ouvindo.', ['Agradecer é ótimo.', null, 'Sorrir não revela nada.', 'Responder é normal; o cuidado é com o conteúdo.']);
  q('hc_4#1', 'Antes de viajar para jogar, confira documentos, regras locais e obrigações fiscais.', ['Só o hotel deixa de fora coisas que podem impedir você de jogar.', null, 'Sem conferir, você corre riscos legais.', 'O câmbio é só uma parte.']);
  q('hc!ex#0', 'Antes de uma grande série, foque nas situações do formato do evento.', ['Cash com 100 bb é outro jogo.', null, 'Heads-up é só o fim do torneio.', 'Sem preparação você desperdiça a série.']);
  q('hc!ex#1', 'Em entrevistas durante o evento, não revele leituras: os adversários estão ouvindo.', ['Falar muito aumenta o risco de revelar algo.', null, 'Criticar adversários cria inimigos e revela leituras.', 'Prometer vitória é pressão desnecessária.']);
  // ca · Carreira
  q('ca_1#0', 'Fora da mesa, o maior patrimônio é a reputação: as oportunidades (times, contratos, parcerias) chegam por pessoas.', ['O stack é patrimônio na mesa.', null, 'O HUD é ferramenta.', 'O rakeback é um benefício pequeno.']);
  q('ca_1#1', 'Ao compartilhar uma mão, deixe o resultado para o fim: assim a discussão fica na decisão, não no que aconteceu (evita o resulting).', ['Resultado primeiro contamina a análise.', null, 'Omitir sempre não é necessário; só no fim.', 'Inventar resultado é desonesto.']);
  q('ca_2#0', 'Makeup é o prejuízo acumulado com o time, pago com lucros futuros antes de haver divisão.', ['Não é bônus.', null, 'Rakeback é retorno da sala.', 'Não é taxa da sala.']);
  q('ca_2#1', 'O lucro primeiro zera o makeup: $1.500 − $1.000 = $500. A sua parte: 50% de $500 = $250.', ['Sobra lucro depois do makeup: não é zero.', null, '$500 é o que sobra antes de dividir.', '$750 divide sem tirar o makeup.']);
  q('ca_3#0', 'As condições de saída e do makeup são cláusulas críticas: definem o risco real do contrato.', ['A cor do logo não importa.', null, 'Horário das aulas é detalhe.', 'Há cláusulas críticas.']);
  q('ca_3#1', 'Antes de assinar, converse com jogadores atuais e antigos do time: quem viveu sabe como o contrato funciona na prática.', ['Assinar rápido aumenta o risco.', null, 'Não ler é o pior cenário.', 'Pedir adiantamento não esclarece o contrato.']);
  q('ca_4#0', 'O que mais convence um time é evolução documentada e volume: mostra processo.', ['Um torneio ganho pode ser sorte.', null, 'Seguidores não medem habilidade.', 'Um HUD bonito não mostra resultados.']);
  q('ca_4#1', 'Diante de uma dúvida numa entrevista técnica, seja claro sobre ela e mostre como investigaria: pensar vale mais que acertar tudo.', ['Inventar é descoberto e destrói a confiança.', null, 'Mudar de assunto parece fuga.', 'Desistir mostra pouca resiliência.']);
  q('ca_5#0', 'Numa transmissão de poker, use atraso: protege você de quem assiste e passa informação aos adversários.', ['Mostrar as cartas ao vivo entrega a sua mão.', null, 'Falar das mãos dos outros é antiético.', 'Há um cuidado essencial: o atraso.']);
  q('ca_5#1', 'Raciocínio e revisões constroem credibilidade: mostram como você pensa.', ['Prints de prêmios mostram resultado, não habilidade.', null, 'Criticar adversários afasta pessoas.', 'Promessas sem processo não convencem.']);
  q('ca_6#0', 'Para uma aula de coaching, leve dados, perguntas e mãos escolhidas: a preparação multiplica a aula.', ['Sem preparação, a aula rende pouco.', null, 'Só o saldo não mostra o que corrigir.', 'Reclamações não são material de estudo.']);
  q('ca_6#1', 'Ensinar obriga a explicar o porquê, e explicar revela o que você não entende.', ['Dinheiro não é o motivo do aprendizado.', null, 'Não é obrigatório.', 'Ajuda, e muito.']);
  q('ca!ex#0', 'O lucro de $300 nem zera o makeup de $500 (ainda faltam $200): você recebe $0.', ['$150 divide sem zerar o makeup.', null, '$300 ignora o makeup.', '$400 não corresponde à conta.']);
  q('ca!ex#1', 'O melhor material é um portfólio com evolução documentada: processo e volume.', ['Um print de prêmio pode ser sorte.', null, 'Seguidores não medem habilidade.', 'Uma recomendação ajuda, mas não substitui dados.']);
  q('ca!ex#2', 'O contrato mais equilibrado tem reset anual do makeup e saída clara: limita o risco da variância para os dois lados.', ['Makeup que nunca zera e sem saída prende você indefinidamente.', null, 'Sem contrato escrito, não há proteção.', 'Os contratos são muito diferentes entre si.']);
})(typeof window !== 'undefined' ? window : globalThis);
