/* Escola do Ás — "Como se faz": o método de cada tipo de exercício gerado pelo app.
   Regra do curso: nada é cobrado sem antes ser ensinado. Cada gerador e cada treino tem aqui o passo a passo,
   um exemplo resolvido (com números diferentes dos do exercício) e pistas próprias, em forma de pergunta.
   O app mostra o método aberto nas primeiras vezes em que o aluno encontra o exercício, nas lições do conceito
   e sempre que o aluno pede ("Como se faz?"). Formato: chave: { t, steps: [...], ex, hints: [...] }. */
(function (g) {
  'use strict';
  const C = g.Curriculum;
  C.HOW = {
    // ---------- Nível 0 ----------
    cartaMaior: { t: 'Qual carta vale mais', steps: ['Ignore o naipe: ele não muda o valor da carta.', 'Use a ordem, da menor para a maior: 2, 3, 4, 5, 6, 7, 8, 9, 10, valete (J), dama (Q), rei (K), ás (A).', 'A carta que aparece mais à direita nessa ordem vale mais.'], ex: 'J♣ contra 9♥: na ordem, o 9 vem antes do valete. O valete vale mais.', hints: ['O naipe importa para dizer qual carta vale mais?', 'Onde cada carta fica na ordem 2, 3, … 10, J, Q, K, A?'] },
    acoes: { t: 'Quais ações são permitidas', steps: ['Veja se alguém já apostou nesta etapa.', 'Se ninguém apostou: você pode passar (não colocar nada) ou apostar.', 'Se alguém apostou: você pode desistir, pagar (igualar) ou aumentar. Passar deixa de existir.'], ex: 'Ana apostou 4. Na sua vez, as opções são desistir, pagar 4 ou aumentar. Passar não é permitido.', hints: ['Alguém já colocou fichas nesta etapa?', 'Depois de uma aposta, dá para continuar sem colocar nada?'] },
    quemFala: { t: 'Quem coloca os blinds e quem fala primeiro', steps: ['Encontre o botão (o dealer da mão).', 'O primeiro jogador à esquerda do botão coloca o small blind.', 'O seguinte coloca o big blind.', 'Antes do flop, fala primeiro quem está à esquerda do big blind; depois do flop, o primeiro ainda na mão à esquerda do botão.'], ex: 'Mesa: Ana, Beto, Cida, Davi (em sentido horário), botão com Davi. Small blind: Ana. Big blind: Beto. Primeiro a falar antes do flop: Cida.', hints: ['Quem está com o botão?', 'Quem senta logo à esquerda dele?'] },
    pote: { t: 'Contar o pote', steps: ['Some o que cada jogador colocou, um por um.', 'Quem desistiu deixa no pote o que já tinha colocado (por exemplo, o small blind).', 'Quem pagou um aumento colocou o valor total do aumento, não só a diferença para o blind.'], ex: 'Blinds 1/2. Um jogador aumenta para 6, o small blind desiste e o big blind paga. Pote: 6 (quem aumentou) + 1 (small blind, que ficou) + 6 (big blind) = 13.', hints: ['Quanto cada jogador colocou no total?', 'O small blind que desistiu levou as fichas de volta?'] },
    // ---------- Nível 1 ----------
    posicao: { t: 'Quem está em posição', steps: ['Depois do flop, a ordem de fala é SB, BB, UTG, HJ, CO, BTN.', 'Entre os jogadores que restaram, quem vem por último nessa ordem está em posição.', 'Falar por último é vantagem: você vê o que os outros fizeram antes de decidir.'], ex: 'Restaram o BB e o CO. Na ordem SB, BB, UTG, HJ, CO, BTN, o CO vem depois: o CO está em posição.', hints: ['Qual é a ordem de fala depois do flop?', 'Dos que restaram, quem fala por último?'] },
    stackef: { t: 'Stack efetivo', steps: ['Olhe as fichas de cada jogador envolvido.', 'O stack efetivo é o menor deles.', 'É o máximo que pode trocar de mãos entre vocês: ninguém ganha de um jogador mais do que ele tem.'], ex: 'Você tem 150 bb e o adversário tem 80 bb. Stack efetivo: 80 bb.', hints: ['Qual dos dois tem menos fichas?', 'Você consegue ganhar dele mais fichas do que ele tem?'] },
    sidepot: { t: 'Pote principal e pote paralelo', steps: ['Quem está all-in só disputa o que conseguiu igualar.', 'Pote principal: o valor do all-in vezes o número de jogadores que pagaram (incluindo quem foi all-in).', 'Pote paralelo: tudo o que os outros colocaram a mais. Só eles disputam esse pote.'], ex: 'Ana vai all-in com 10. Beto e Cida pagam. Depois Beto aposta 30 e Cida paga. Principal: 3 × 10 = 30. Paralelo: 30 + 30 = 60, só entre Beto e Cida.', hints: ['Quanto o jogador all-in conseguiu colocar?', 'Quem colocou fichas além disso?'] },
    stackbb: { t: 'Converter fichas em big blinds', steps: ['Encontre o valor do big blind: é o número maior dos blinds (em 300/600, o big blind é 600).', 'Divida as suas fichas pelo big blind.', 'O resultado é o seu stack em big blinds (bb). É assim que se compara qualquer stack em qualquer nível.'], ex: '9.000 fichas com blinds 250/500: 9.000 ÷ 500 = 18 bb.', hints: ['Qual dos dois números dos blinds é o big blind?', 'Quantas vezes o big blind cabe nas suas fichas?'] },
    winrate: { t: 'Calcular a taxa de ganho (bb/100)', steps: ['A taxa é medida em big blinds ganhos a cada 100 mãos: "bb/100".', 'Descubra quantos blocos de 100 mãos você jogou: mãos ÷ 100.', 'Divida o que ganhou (em bb) por esse número de blocos.'], ex: 'Você ganhou 600 bb em 20.000 mãos. Blocos de 100: 20.000 ÷ 100 = 200. Taxa: 600 ÷ 200 = 3 bb/100.', hints: ['Quantos blocos de 100 mãos há nesse total?', 'Quanto você ganhou, em média, em cada bloco?'] },
    combos: { t: 'Contar combinações de mãos', steps: ['Cada valor tem 4 cartas, uma por naipe.', 'Par (ex.: 99): escolha 2 das 4 cartas do valor: 4 × 3 ÷ 2 = 6 combinações. Se algumas cartas desse valor estão visíveis, conte só as que sobram (3 cartas dão 3; 2 cartas dão 1).', 'Duas cartas diferentes (ex.: KQ): 4 × 4 = 16 ao todo. Do mesmo naipe (KQs): 4. De naipes diferentes (KQo): 12.'], ex: 'Quantos AK existem? 4 ases × 4 reis = 16. Se um ás está na mesa, sobram 3 ases: 3 × 4 = 12.', hints: ['Quantas cartas desse valor ainda podem estar com o adversário?', 'É par ou são duas cartas diferentes?'] },
    regra24: { t: 'A regra do 2 e do 4', steps: ['Conte as suas outs (as cartas que completam o seu jogo).', 'Falta só uma carta (do turn para o river): multiplique as outs por 2.', 'Faltam duas cartas e você vai ver as duas (all-in no flop): multiplique as outs por 4.', 'O resultado é a chance aproximada, em porcentagem.'], ex: '8 outs no flop, all-in: 8 × 4 = 32%. As mesmas 8 outs no turn: 8 × 2 = 16% (o número exato é 17%).', hints: ['Quantas cartas ainda vão sair?', 'Por quanto multiplicar quando falta uma carta só?'] },
    bbpreco: { t: 'O preço para defender o big blind', steps: ['Você já colocou 1 bb. Para pagar um aumento para X, coloca só X − 1.', 'Pote final = o aumento + o small blind (0,5) + o seu total (X).', 'Chance mínima para pagar = o que você coloca ÷ pote final.'], ex: 'Aumento para 3 bb, small blind desiste. Você coloca 3 − 1 = 2. Pote final: 3 + 0,5 + 3 = 6,5. Precisa de 2 ÷ 6,5 ≈ 31%.', hints: ['Quanto você já tinha colocado antes do aumento?', 'Quanto vai ter no pote se você pagar?'] },
    ev: { t: 'O valor esperado (EV) de um blefe', steps: ['EV é a média do que você ganha ou perde se a mesma situação se repetir muitas vezes.', 'Quando ele desiste, você ganha o pote. Quando ele paga, você perde a aposta.', 'EV = (chance de desistir × pote) − (chance de pagar × aposta).'], ex: 'Pote 50, você blefa 50, ele desiste 60% das vezes. EV = 0,6 × 50 − 0,4 × 50 = 30 − 20 = +10. O blefe dá lucro.', hints: ['Quanto você ganha quando ele desiste?', 'Quanto você perde quando ele paga?'] },
    implied: { t: 'Implied odds: o que precisa ganhar depois', steps: ['Pagar custa a aposta. Você perde esse valor nas vezes em que não completa.', 'Nas vezes em que completa, ganha o pote atual mais a aposta, mais o que conseguir arrancar no river (X).', 'Empate: chance de completar × (pote + aposta + X) = chance de não completar × aposta. Resolva para X.'], ex: 'Pote 60, aposta 30, você completa 20%. 0,2 × (90 + X) = 0,8 × 30 = 24. Então 90 + X = 120, e X = 30.', hints: ['Quanto você perde, em média, nas vezes em que não completa?', 'Quanto precisa ganhar nas vezes em que completa para compensar?'] },
    blefratio: { t: 'Quantos blefes levar ao river', steps: ['Escreva a aposta como fração do pote (meio pote = 0,5; pote = 1).', 'Quem paga arrisca a aposta para ganhar o pote mais a aposta. Ele precisa ganhar aposta ÷ (pote + 2 × aposta) para pagar.', 'No equilíbrio, os blefes são exatamente essa parte das suas apostas. Em quantidade: blefes = valor × aposta ÷ (pote + aposta).'], ex: 'Aposta do tamanho do pote (1). Parte de blefes: 1 ÷ 3 = 33%. Com 10 combinações de valor: 10 × 1 ÷ 2 = 5 blefes.', hints: ['Quanto o adversário arrisca e quanto ganha ao pagar?', 'Que chance ele precisa ter para pagar?'] },
    semiblefe: { t: 'Quantas desistências um semi-blefe precisa', steps: ['Calcule o resultado médio quando ele paga: chance de completar × o que ganha − chance de não completar × o que perde.', 'Quando ele desiste, você ganha o pote.', 'Empate: desistências × pote = (1 − desistências) × perda média quando ele paga.'], ex: 'Pote 100, all-in de 100, você completa 25%. Quando ele paga: 0,25 × 200 − 0,75 × 100 = −25. Empate: d × 100 = (1 − d) × 25 → d = 20%.', hints: ['Quanto você ganha ou perde, em média, quando ele paga?', 'E quando ele desiste?'] },
    spr: { t: 'Calcular o SPR', steps: ['SPR é stack efetivo ÷ pote no flop.', 'Some o pote: o que cada jogador colocou antes do flop, mais os blinds de quem desistiu.', 'Stack efetivo no flop: o menor stack menos o que ele já colocou.'], ex: 'Você abre para 3 bb e o botão paga; os blinds desistem. Pote: 3 + 3 + 0,5 + 1 = 7,5. Stack efetivo: 100 − 3 = 97. SPR = 97 ÷ 7,5 ≈ 13.', hints: ['Quanto há no pote quando o flop sai?', 'Quanto ainda sobra de stack efetivo?'] },
    // ---------- Nível 2 ----------
    bloq: { t: 'Bloqueadores: contar o que sobrou', steps: ['Cada valor tem 4 cartas. Tire as que você vê: as da mesa e as da sua mão.', 'Par desse valor: com N cartas restantes, são N × (N − 1) ÷ 2 combinações (3 cartas dão 3; 2 cartas dão 1).', 'Duas cartas diferentes: multiplique as que sobraram de cada valor.'], ex: 'Mesa K♠ 8♦ 2♣, você tem K♥. Reis restantes: 4 − 2 = 2. Combinações de KK: 2 × 1 ÷ 2 = 1. Combinações de K8: 2 × 3 = 6.', hints: ['Quantas cartas desse valor você consegue ver?', 'Quantas sobram para o adversário?'] },
    bf: { t: 'Fator de bolha', steps: ['O fator de bolha diz quanto vale mais perder fichas do que ganhar, por causa dos prêmios (ICM).', 'Chance mínima para pagar um all-in, sem outras fichas no pote = fator ÷ (1 + fator).', 'Fator 1 = sem ICM: 50%. Quanto maior o fator, mais apertado você precisa jogar.'], ex: 'Fator 1,5: 1,5 ÷ 2,5 = 60%. Sem ICM você precisaria de 50%.', hints: ['Qual seria a chance necessária sem ICM?', 'Como o fator muda essa conta?'] },
    // ---------- Nível 3 ----------
    bounty: { t: 'Torneio com bounty: o preço com a recompensa', steps: ['Descubra quanto vale cada ficha: o valor que cada inscrição põe no prêmio ÷ as fichas iniciais.', 'Converta a bounty em fichas: bounty ÷ valor da ficha.', 'Chance mínima = o que você paga ÷ (pote final + bounty em fichas).'], ex: '$10 de prêmio por 10.000 fichas: cada ficha vale $0,001. Bounty de $5 = 5.000 fichas. Pagar 2.000 para um pote de 8.000: 2.000 ÷ (8.000 + 5.000) ≈ 15%.', hints: ['Quanto vale uma ficha em dinheiro?', 'Quantas fichas a bounty vale?'] },
    hudeal: { t: 'Valor justo do stack no heads-up final', steps: ['O 2º prêmio já é garantido para os dois.', 'A diferença entre o 1º e o 2º está em disputa.', 'Com jogadores de nível parecido, a sua parte da diferença é a sua fatia das fichas. Valor = 2º prêmio + fatia × (1º − 2º).'], ex: '1º: $500, 2º: $300. Você tem 40% das fichas. Valor: $300 + 0,4 × $200 = $380.', hints: ['Quanto os dois já têm garantido?', 'Quanto ainda está em disputa?'] },
    impacto: { t: 'Qual erro corrigir primeiro', steps: ['O custo de um erro = quanto ele custa cada vez × quantas vezes acontece.', 'Calcule os dois em bb a cada 100 mãos.', 'Corrija primeiro o que custa mais no total, mesmo que pareça menor em cada mão.'], ex: 'Erro A: 0,5 bb, 6 vezes a cada 100 mãos → 3 bb/100. Erro B: 10 bb, 0,2 vez → 2 bb/100. Primeiro o A.', hints: ['Quanto cada erro custa no total, a cada 100 mãos?', 'Um erro frequente e pequeno pode custar mais que um raro e grande?'] },
    // ---------- Nível 4 ----------
    ic: { t: 'Intervalo de confiança da taxa de ganho', steps: ['Conte os blocos de 100 mãos: mãos ÷ 100.', 'Tire a raiz quadrada desse número.', 'Margem de 95% ≈ 1,96 × desvio padrão ÷ raiz. A sua taxa real deve estar entre a medida menos e a medida mais essa margem.'], ex: '40.000 mãos = 400 blocos. Raiz de 400 = 20. Desvio 90: 1,96 × 90 ÷ 20 ≈ ± 9 bb/100.', hints: ['Quantos blocos de 100 mãos há?', 'Qual é a raiz quadrada desse número?'] },
    roi: { t: 'Calcular o ROI', steps: ['ROI = lucro ÷ total investido, em porcentagem.', 'O investimento é a soma das inscrições pagas.', 'Se houve prejuízo, o ROI é negativo.'], ex: 'Investiu $4.000 e lucrou $600: 600 ÷ 4.000 = 15%.', hints: ['Quanto você lucrou e quanto investiu?', 'Que parte do investimento o lucro representa?'] },
    overlay: { t: 'Calcular o overlay', steps: ['Quanto de cada inscrição vai para o prêmio: inscrição menos a taxa.', 'Multiplique pelo número de inscritos: é o prêmio arrecadado.', 'Overlay = garantido − arrecadado (se for positivo). É dinheiro que a sala põe a mais.'], ex: '$22 com 10% de taxa: $19,80 vão para o prêmio. 400 inscritos: $7.920. Garantido de $10.000: overlay de $2.080.', hints: ['Quanto de cada inscrição vai para o prêmio?', 'Quanto foi arrecadado no total?'] },
    rakeback: { t: 'Taxa efetiva com rake e rakeback', steps: ['Comece pela taxa antes do rake.', 'Tire o rake pago.', 'Some de volta a parte do rake que você recebe (rakeback).'], ex: 'Taxa antes do rake: 6 bb/100. Rake: 8 bb/100. Rakeback de 30%: 6 − 8 + 0,3 × 8 = 0,4 bb/100.', hints: ['Quanto o rake tira da sua taxa?', 'Quanto do rake volta para você?'] },
    // ---------- Nível 5 ----------
    makeup: { t: 'Makeup num time (staking)', steps: ['Makeup é o prejuízo acumulado que você ainda deve ao time.', 'O lucro do mês primeiro zera o makeup.', 'Só o que sobra é dividido, pela porcentagem combinada.'], ex: 'Makeup de $500, lucro de $2.000, divisão 50%: sobra $1.500, a sua parte é $750.', hints: ['O lucro do mês primeiro paga o quê?', 'Sobrou quanto para dividir?'] },
    // ---------- Decisões de mesa (aplicação) ----------
    appEVBluff: { t: 'Blefar ou não no river', steps: ['O blefe arrisca a aposta para ganhar o pote.', 'Desistências necessárias = aposta ÷ (pote + aposta).', 'Compare com a frequência com que ele desiste. Se desiste mais que isso, blefe.'], ex: 'Pote 60, aposta 40: precisa de 40 ÷ 100 = 40% de desistências. Ele desiste 55%: blefe.', hints: ['Quanto você arrisca e quanto pode ganhar?', 'Com que frequência ele precisa desistir?'] },
    appMDF: { t: 'Pagar ou desistir no river contra uma aposta', steps: ['Chance necessária = aposta ÷ (pote + 2 × aposta).', 'Você só ganha contra os blefes dele. Chance real = blefes ÷ (blefes + valor).', 'Pague se a chance real for maior que a necessária.'], ex: 'Pote 50, aposta 50: precisa de 50 ÷ 150 = 33%. Ele tem 6 de valor e 4 blefes: 4 ÷ 10 = 40%. Pague.', hints: ['Contra quais mãos dele você ganha?', 'Quanto você precisa ganhar para pagar?'] },
    appSemi: { t: 'Semi-blefe ou passar', steps: ['Passar: você vê o river de graça e ganha o pote quando completa.', 'All-in: calcule a média (desistências × pote) + (pagamentos × resultado quando ele paga).', 'Escolha o que der mais.'], ex: 'Pote 100, você completa 20%. Passar vale 0,2 × 100 = 20. All-in de 100 com 40% de desistências: 0,4 × 100 + 0,6 × (0,2 × 200 − 0,8 × 100) = 40 − 24 = 16. Passar é melhor.', hints: ['Quanto vale passar, em média?', 'Com que frequência ele desiste do all-in?'] },
    appSPR: { t: 'Colocar tudo ou desistir com SPR baixo', steps: ['SPR = stack ÷ pote. Abaixo de 4, o pote já é grande perto do que sobra.', 'Com SPR baixo, um par alto com bom kicker vale ir até o fim: ele ganha de muitos blefes, projetos e mãos piores.', 'Com SPR alto (acima de 10), um só par raramente aguenta três ruas de apostas.'], ex: 'Pote 30, stack 60: SPR 2. Com top pair e bom kicker, vá até o fim.', hints: ['Quanto sobra de stack em relação ao pote?', 'Que mãos ele pode ter nessa linha?'] },
    appBBdef: { t: 'Defender o big blind', steps: ['Calcule o preço: (aumento − 1) ÷ (aumento + 0,5 + aumento).', 'O preço costuma ser bom: perto de 20% a 30%.', 'Mas você joga fora de posição: defenda mãos que fazem pares altos, projetos ou são do mesmo naipe e próximas. Desista das desconectadas e fracas.'], ex: 'Aumento para 2,5: você paga 1,5 para um pote de 5,5, precisa de 27%. Defenda KTs e 76s; desista de K3o.', hints: ['Quanto você precisa ganhar para pagar?', 'A mão joga bem depois do flop, fora de posição?'] },
    appImplied: { t: 'Pagar com projeto contando o que vem depois', steps: ['Pelas pot odds: aposta ÷ (pote + 2 × aposta). Compare com a sua chance de completar.', 'Se faltar pouco, conte o que você ganha a mais quando completa (implied odds).', 'EV = chance × (pote + aposta + ganho extra) − (1 − chance) × aposta. Pague se der positivo.'], ex: 'Pote 40, aposta 20, chance 20%. Pot odds: 20 ÷ 80 = 25%: falta. Ganho extra de 30: 0,2 × 90 − 0,8 × 20 = 18 − 16 = +2. Pague.', hints: ['As pot odds sozinhas bastam?', 'Quanto ele costuma pagar quando você completa?'] },
    appBounty: { t: 'Pagar um all-in com bounty', steps: ['Converta a bounty em fichas: bounty ÷ valor de cada ficha.', 'Chance necessária = o que você paga ÷ (pote final + bounty em fichas).', 'Compare com a sua chance contra o range dele.'], ex: 'Pagar 2.000 num pote de 6.000, bounty vale 4.000 fichas: 2.000 ÷ 10.000 = 20%. Com 35%, pague.', hints: ['Quanto a bounty vale em fichas?', 'Qual chance você precisa ter?'] },
    appDeal: { t: 'Aceitar ou recusar um acordo', steps: ['Valor justo = 2º prêmio + a sua fatia das fichas × (1º − 2º).', 'Compare com a proposta.', 'Abaixo do valor justo: recuse ou peça mais. Acima: aceite, se o adversário não for mais fraco que você.'], ex: '1º $800, 2º $400, você tem 60%: $400 + 0,6 × $400 = $640. Proposta de $600: abaixo, peça mais.', hints: ['Qual é o valor justo do seu stack?', 'A proposta está acima ou abaixo dele?'] },
    appBlefes: { t: 'Quantos projetos que falharam usar como blefe', steps: ['Proporção de blefes no equilíbrio = aposta ÷ (pote + 2 × aposta).', 'Em quantidade: blefes = valor × aposta ÷ (pote + aposta).', 'Escolha como blefes os projetos com melhores bloqueadores; passe com o resto.'], ex: 'Aposta do tamanho do pote, 8 combinações de valor: 8 × 1 ÷ 2 = 4 blefes.', hints: ['Quantos blefes cabem para cada combinação de valor?', 'Blefar com todos deixaria pagar lucrativo para ele?'] },
    // ---------- Treinos ----------
    ranking: { t: 'Quem vence no showdown', steps: ['Para cada jogador, junte as 2 cartas dele com as 5 da mesa.', 'Escolha as 5 melhores entre essas 7: é o jogo dele.', 'Compare as categorias (carta alta < par < dois pares < trinca < sequência < flush < full house < quadra < straight flush).', 'Mesma categoria: compare carta por carta, da mais alta para a mais baixa.'], ex: 'Mesa K♠ 9♦ 6♣ 4♥ 2♠. A tem K♦ 3♣: par de reis. B tem 9♣ 9♥: trinca de noves. Trinca vence par: B.', hints: ['Qual é a melhor combinação de 5 cartas de cada um?', 'Quatro cartas em sequência formam uma sequência?'] },
    besthand: { t: 'Qual é a sua melhor mão', steps: ['Junte as suas 2 cartas com as 5 da mesa: são 7.', 'Procure da mais forte para a mais fraca: flush (5 do mesmo naipe), sequência (5 seguidas), trinca, dois pares, par.', 'Lembre: sequência e flush precisam de 5 cartas. Quatro não bastam.'], ex: 'Você: 7♥ 8♥. Mesa: 9♣ 10♦ J♠ 2♥ 3♦. 7-8-9-10-J: sequência.', hints: ['Há cinco cartas do mesmo naipe?', 'Há cinco cartas seguidas?'] },
    rfi: { t: 'Abrir ou desistir', steps: ['Se ninguém entrou antes, a decisão é aumentar ou desistir. Nada de limp.', 'Veja a sua posição: quanto mais tarde (CO, BTN), mais mãos você abre.', 'Confira se a mão está na tabela de abertura daquela posição.'], ex: 'K9s no UTG: fora da tabela, desista. A mesma K9s no BTN: dentro, aumente.', hints: ['Qual é a sua posição?', 'A mão está na tabela dessa posição?'] },
    outs: { t: 'Contar outs', steps: ['Diga qual jogo você quer completar (sequência ou flush).', 'Liste as cartas que completam esse jogo.', 'Tire as que você já vê (na sua mão e na mesa). As que sobram são as outs.', 'Projeto de flush: 13 cartas do naipe − 4 visíveis = 9 outs. Sequência aberta nas duas pontas: 8. Por dentro (gutshot): 4.'], ex: 'Você: 9♠ 8♠. Flop: 7♦ 6♣ K♠. Sequência aberta: qualquer 10 ou 5 completa. 4 dezes + 4 cincos = 8 outs.', hints: ['Que jogo você quer completar?', 'Quantas cartas desse tipo você ainda não viu?'] },
    potodds: { t: 'Pot odds, defesa mínima (MDF) e blefe', steps: ['Para pagar: chance necessária = o que você paga ÷ pote final (pote + aposta + o seu pagamento).', 'Para defender (MDF): continue com pelo menos pote ÷ (pote + aposta) do seu range.', 'Para blefar: ele precisa desistir aposta ÷ (pote + aposta) das vezes.'], ex: 'Pote 20, aposta 10. Pagar: 10 ÷ 40 = 25%. MDF: 20 ÷ 30 = 67%. Blefe de 10 num pote de 20: 10 ÷ 30 = 33% de desistências.', hints: ['Quanto você coloca e quanto pode ganhar?', 'Qual é o pote final se você pagar?'] },
    callfold: { t: 'Pagar ou desistir com projeto', steps: ['Conte as outs.', 'No turn faltam 46 cartas: chance = outs ÷ 46.', 'Preço = aposta ÷ (pote + 2 × aposta).', 'Pague se a chance for maior que o preço.'], ex: '9 outs no turn: 9 ÷ 46 ≈ 20%. Aposta de 10 num pote de 30: 10 ÷ 50 = 20%. Empate: tanto faz.', hints: ['Quantas outs você tem?', 'Quanto você precisa ganhar para pagar?'] },
    texture: { t: 'Classificar o flop', steps: ['Três cartas do mesmo naipe: monotone.', 'Duas cartas do mesmo valor: pareada.', 'As três cabem numa sequência de cinco, ou há duas do mesmo naipe e cartas próximas: molhada (muitos projetos).', 'Sem nada disso: seca.'], ex: 'J♥ 10♥ 4♣: duas copas e J-10 próximas: molhada. K♠ 7♦ 2♣: naipes diferentes e cartas distantes: seca.', hints: ['Há duas ou três cartas do mesmo naipe?', 'As cartas estão próximas o bastante para sequências?'] },
    equity: { t: 'Estimar a equity antes do flop', steps: ['Par contra par menor: cerca de 80%.', 'Par contra duas cartas maiores: cerca de 55%.', 'Duas cartas maiores contra duas menores: cerca de 65%.', 'Mão dominada (mesma carta, kicker pior): cerca de 30%.', 'Mesmo naipe acrescenta 2 a 3 pontos.'], ex: 'JJ contra AK: par contra duas maiores, cerca de 55% para o JJ.', hints: ['É par contra par, par contra cartas altas ou cartas contra cartas?', 'Alguém está dominado?'] },
    pushfold: { t: 'Empurrar ou desistir com stack curto', steps: ['Com 15 bb ou menos, a decisão é all-in ou desistir.', 'Quanto menos fichas, mais mãos você empurra.', 'Consulte a tabela de equilíbrio (Nash) da sua posição e do seu stack.'], ex: '8 bb no botão: empurre quase todas as mãos com ás, todos os pares e muitas cartas altas.', hints: ['Quantos big blinds você tem?', 'Quanto menos fichas, mais ou menos mãos você empurra?'] },
    icm: { t: 'Pagar um all-in com ICM', steps: ['Em fichas, a chance necessária é o preço normal (pot odds).', 'Com prêmios em jogo, perder custa mais que ganhar: some o prêmio de risco (risk premium).', 'Pague só se a sua equity passar do valor com ICM.'], ex: 'Em fichas precisa de 45%; com ICM, 52%. Com 50% de equity: desista.', hints: ['Quanto precisaria em fichas?', 'Quanto o ICM acrescenta?'] },
    bankroll: { t: 'Gestão de banca', steps: ['Divida a banca pelo número de buy-ins da regra (cash: 40 a 50; torneios: 100 ou mais).', 'O resultado é o maior buy-in que você pode jogar.', 'Escolha o limite ou torneio com buy-in igual ou menor que isso.'], ex: 'Banca de $1.000 em cash com 50 buy-ins: $1.000 ÷ 50 = $20 por buy-in, ou seja, NL20.', hints: ['Quantos buy-ins a regra pede?', 'Quanto é a banca dividida por esse número?'] },
  };
})(typeof window !== 'undefined' ? window : globalThis);
