/* Escola do Ás — explicações completas das perguntas das lições e provas (Nível 0).
   Cada entrada: chave da pergunta ("lição#n" ou "módulo!ex#n") → [explicação, [motivo de cada alternativa]].
   O motivo da alternativa correta é null. O app troca a explicação curta original por esta e mostra
   "Onde está o erro" quando o aluno marca uma alternativa errada. */
(function (g) {
  'use strict';
  const C = g.Curriculum, X = (C.QX = C.QX || {});
  const q = (k, e, w) => (X[k] = [e, w]);
  // z1 · O que é poker
  q('z1_1#0', 'O pote é o monte de fichas no meio da mesa: tudo o que os jogadores apostaram naquela partida. Quem vence a partida leva o pote inteiro.', [null, '"Banco" é o termo de cassino para quem guarda o dinheiro; no poker não existe banco jogando contra você.', 'A mesa é o lugar onde se joga; as fichas no meio dela têm nome próprio: pote.', 'O baralho são as cartas, não as fichas.']);
  q('z1_1#1', 'No poker você joga contra as outras pessoas da mesa. As fichas que você ganha saem do bolso delas, e as que você perde vão para elas. A sala só cobra uma pequena taxa (o rake).', ['O cassino não joga contra você no poker: ele só organiza o jogo e cobra uma taxa. Isso é diferente da roleta ou do blackjack.', null, 'Mesmo jogando online, os adversários são pessoas; o computador só distribui as cartas.', 'O dealer apenas distribui as cartas e cuida do pote; ele não joga.']);
  q('z1_1#2', 'O curso ensina o Texas Hold\'em, a versão mais jogada do mundo: duas cartas fechadas para cada jogador e cinco cartas abertas na mesa, que todos usam.', [null, 'O pôquer fechado é uma versão antiga, com cinco cartas na mão e sem cartas na mesa.', 'Truco é outro jogo de cartas, não uma versão do poker.', 'Blackjack é um jogo de cassino contra a banca, não poker.']);
  q('z1_2#0', 'Há dois caminhos para ganhar o pote: chegar ao final com a melhor combinação de cartas, ou fazer todos os outros desistirem antes. O segundo caminho é o que torna o blefe possível.', [null, 'Ter mais fichas ou apostar primeiro não ganha o pote; o que decide é a melhor combinação ou a desistência dos outros.', 'O dealer não ganha partidas, e um ás sozinho não garante nada.', 'Existem, sim, dois jeitos, e entender os dois é a base de toda a estratégia.']);
  q('z1_2#1', 'Quem desiste sai daquela partida e perde o direito ao pote. As fichas que já colocou ficam no pote e vão para quem vencer.', [null, 'As fichas não voltam: o que entrou no pote fica no pote.', 'Quem desiste não ganha nada daquela partida.', 'Quem desiste está fora até a próxima partida.']);
  q('z1_2#2', 'Blefar é apostar para fazer os outros desistirem mesmo sem ter um jogo forte. Funciona porque um jeito de ganhar é todos os outros desistirem.', [null, 'Mostrar as cartas antes não é blefe; no showdown as cartas são mostradas no final.', 'No Texas Hold\'em não se trocam cartas.', 'Desistir cedo é o oposto de blefar: o blefe é apostar com uma mão fraca.']);
  q('z1_3#0', 'Numa única partida, qualquer pessoa pode ganhar, até quem joga mal: as cartas que chegam variam muito. É por isso que o poker não se avalia por uma partida só.', [null, 'No curto prazo a sorte pesa muito: quem joga melhor perde várias partidas.', 'Mais fichas ajudam a pressionar, mas não garantem vencer uma partida.', 'O dealer não joga, portanto não ganha.']);
  q('z1_3#1', 'A habilidade aparece ao longo de muitas partidas. É como uma moeda levemente viciada: em poucas jogadas qualquer lado sai, mas em milhares a vantagem fica clara.', [null, 'Numa partida só, a sorte pode esconder a habilidade.', 'A habilidade aparece sempre que há repetição suficiente; por isso existem jogadores que ganham por anos.', 'A habilidade conta em qualquer formato, cash ou torneio.']);
  q('z1_3#2', 'Avalie a decisão, não o resultado. Se a decisão foi a melhor com o que você sabia, ela foi boa, mesmo que a carta seguinte tenha feito você perder.', [null, 'O resultado de uma partida tem muita sorte; julgar por ele faz você copiar erros que deram certo por acaso.', 'As fichas no fim do dia também dependem muito da sorte.', 'A opinião dos outros não mede a qualidade da decisão; as contas e o raciocínio medem.']);
  q('z1_4#0', 'Os quadros "Pense antes de ler" pedem que você tente responder sozinho antes de ver a explicação. O esforço de tentar lembrar ou deduzir é o que fixa o aprendizado, mesmo quando você erra.', [null, 'Eles não servem para pular nada: são parte da lição.', 'A ideia é raciocinar, não decorar.', 'Eles aparecem na leitura da lição, não durante o jogo.']);
  q('z1_4#1', 'Pouco por dia, com regularidade. Estudar um pouco todo dia e revisar depois fixa muito mais do que estudar muitas horas de uma vez.', [null, 'Muitas lições num dia só sobrecarregam a memória: boa parte é esquecida.', 'Uma vez por mês é espaçado demais: você esquece antes de revisar.', 'Maratonas no fim de semana rendem menos que o mesmo tempo dividido em dias.']);
  q('z1!ex#0', 'Se ninguém mostrou as cartas, ninguém chegou ao showdown: todos os outros desistiram, e o pote foi para quem sobrou. É o segundo jeito de ganhar.', [null, 'Se ela tivesse mostrado a melhor combinação, haveria showdown; o enunciado diz que ela não mostrou.', 'O dealer não escolhe quem ganha.', 'Pagar mais não ganha o pote sozinho; ou os outros desistem, ou a melhor combinação vence.']);
  q('z1!ex#1', 'Uma boa decisão continua boa mesmo quando você perde: a sorte da partida decidiu. Se você repetir aquela decisão muitas vezes, ela ganha fichas no total.', [null, 'Julgar a decisão pelo resultado de uma partida é o erro mais comum de quem começa.', 'Mudar o que está certo por causa de um resultado ruim piora o seu jogo.', 'Dá para saber, sim: avalia-se a decisão pelas informações que você tinha no momento.']);
  // z2 · O baralho
  q('z2_1#0', 'O baralho do poker tem 52 cartas: 13 valores (2 a 10, valete, dama, rei e ás) em 4 naipes. 13 × 4 = 52. Os coringas não são usados.', ['Quarenta é o baralho de jogos como a sueca, sem 8, 9 e 10.', null, 'Cinquenta e quatro seria com os dois coringas, que o poker não usa.', 'Quarenta e oito não corresponde a nenhum baralho de poker: são 13 valores × 4 naipes = 52.']);
  q('z2_1#1', 'O símbolo de copas é ♥ (um coração). Os outros: espadas ♠, ouros ♦ e paus ♣.', ['♠ é espadas.', null, '♦ é ouros.', '♣ é paus.']);
  q('z2_1#2', 'Cada valor aparece uma vez em cada um dos quatro naipes. Por isso existem 4 setes: 7♠, 7♥, 7♦ e 7♣.', ['Um seria só um naipe; cada valor existe nos quatro.', 'São quatro, não dois: um por naipe.', null, 'Treze é o número de valores em cada naipe, não o de setes.']);
  q('z2_2#0', 'O ás (A) é a carta mais alta. A ordem, da menor para a maior: 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A.', ['O rei fica logo abaixo do ás.', null, 'A dama fica abaixo do rei e do ás.', 'O 10 fica abaixo de valete, dama, rei e ás.']);
  q('z2_2#1', 'O T representa o 10, de "ten" (dez em inglês). Assim todo valor cabe em um caractere só: 2 a 9, T, J, Q, K, A.', ['O três é escrito como 3.', null, 'O rei é o K, de "king".', 'Não existe trunfo no poker.']);
  q('z2_2#2', 'Na ordem 9, 10 (T), J, Q, a maior é a dama (Q).', ['O valete (J) fica logo abaixo da dama.', 'O 9 é a menor das quatro.', null, 'T é o 10, que fica abaixo de J e Q.']);
  q('z2_3#0', 'No Texas Hold\'em nenhum naipe vale mais que outro. Um ás de copas e um ás de espadas valem exatamente o mesmo.', ['Copas não vale mais que os outros naipes.', 'Espadas também não vale mais; em alguns jogos há ordem de naipes, mas não no Texas Hold\'em.', null, 'Ouros vale o mesmo que os outros naipes.']);
  q('z2_3#1', 'Os naipes servem para formar combinações em que todas as cartas são do mesmo naipe, principalmente o flush (cinco cartas do mesmo naipe).', [null, 'Naipes nunca desempatam no Texas Hold\'em: com jogos iguais, o pote é dividido.', 'Quem começa é decidido pelo botão, não pelo naipe.', 'Eles servem, sim: sem naipes não existiria flush.']);
  q('z2_4#0', '"Ah" é o ás de copas: A de ás e h de hearts (copas, em inglês). Os outros naipes: s = espadas, d = ouros, c = paus.', [null, 'O ás de espadas seria "As" (s de spades).', 'A letra depois do valor é o naipe, não uma descrição.', 'Ás e rei seria "AK".']);
  q('z2_4#1', '"AKs" é ás e rei do mesmo naipe: o "s" vem de suited, "do mesmo naipe".', [null, 'Naipes diferentes seria "AKo" (o de offsuit).', 'Dois ases seria "AA".', 'Uma carta específica seria escrita com o naipe de cada uma, como "As Kh".']);
  q('z2_4#2', 'Pares são escritos com o valor repetido: um par de noves é "99".', ['"9s" seria um nove de espadas.', null, '"o" (offsuit) só se usa com duas cartas de valores diferentes.', 'Não se usa esse formato: o par é só "99".']);
  q('z2!ex#0', 'Existem 4 damas, uma por naipe: Q♠, Q♥, Q♦ e Q♣.', ['Cada valor aparece nos quatro naipes, não em um só.', 'São quatro, uma por naipe.', null, 'Treze é o número de valores em cada naipe.']);
  q('z2!ex#1', 'Da menor para a maior: valete (J), dama (Q), rei (K), ás (A).', [null, 'Aí o rei aparece antes da dama: a ordem certa é J, Q, K, A.', 'Essa é a ordem da maior para a menor.', 'A dama é maior que o valete, então Q não pode vir antes de J.']);
  q('z2!ex#2', '"T8o": T é o 10, 8 é o oito e o "o" (offsuit) quer dizer naipes diferentes.', [null, 'T é o 10, não o três; e "o" é naipes diferentes.', 'Do mesmo naipe seria "T8s".', 'Par de oitos seria "88".']);
  // z3 · As combinações
  q('z3_1#0', 'Cada jogador recebe 2 cartas fechadas, que só ele vê. As outras 5 são abertas na mesa e servem para todos.', [null, 'Cinco são as cartas da mesa, que todos usam.', 'Sete é o total que cada jogador pode usar: as 2 dele mais as 5 da mesa.', 'No Texas Hold\'em são 2 cartas, não 3.']);
  q('z3_1#1', 'O jogo final é sempre de 5 cartas: as 5 melhores entre as 7 disponíveis (2 suas + 5 da mesa).', ['Duas são só as suas cartas; o jogo final usa 5.', null, 'Sete são as disponíveis; você escolhe as 5 melhores.', 'Quatro não basta: toda combinação tem 5 cartas.']);
  q('z3_1#2', 'Sim. Vale a melhor combinação de 5 cartas, de onde quer que venham. Se as 5 da mesa formam o melhor jogo, você "joga a mesa", e quem também não tiver nada melhor empata com você.', [null, 'Não é obrigatório usar as suas cartas: você pode usar uma, as duas ou nenhuma.', 'A regra vale em qualquer formato.', 'Não depende de ter ás.']);
  q('z3_2#0', 'Entre dois pares simples, vence o de valor mais alto: par de dez vence par de quatros.', [null, 'O 4 é mais baixo que o 10.', 'Os valores são diferentes, então não há empate.', 'O naipe nunca desempata no Texas Hold\'em.']);
  q('z3_2#1', 'Kicker é a carta que desempata quando dois jogadores têm a mesma combinação. Exemplo: dois pares de reis; vence quem tiver a carta seguinte mais alta.', [null, 'O par mais alto é a própria combinação, não o desempate.', 'A última carta da mesa é o river.', 'Não é uma aposta: é uma carta.']);
  q('z3_2#2', 'Em dois pares, compara-se primeiro o par mais alto: ases contra reis. Ases vencem, então A-A-3-3 ganha, mesmo com o segundo par baixo.', [null, 'Os reis perdem para os ases, que são comparados primeiro; o segundo par só conta se o primeiro empatar.', 'Os pares mais altos são diferentes, então não há empate.', 'O kicker só entra se os dois pares empatarem.']);
  q('z3_3#0', 'A sequência (cinco valores seguidos) vence a trinca, porque é mais rara.', ['A trinca é mais comum, por isso vale menos.', null, 'São combinações diferentes, e a sequência está acima.', 'O naipe não muda a ordem das combinações.']);
  q('z3_3#1', 'A-2-3-4-5 é válida: o ás pode ser a carta mais baixa (essa sequência se chama roda). Mas a sequência não dá a volta: K-A-2 não vale.', ['Q-K-A-2-3 dá a volta pelo ás, e isso não vale.', null, 'J-Q-K-A-3 pula do ás para o 3: não são valores seguidos.', '2-4-6-8-10 tem buracos: não são valores seguidos.']);
  q('z3_3#2', 'Os naipes da sequência podem ser quaisquer. Se as cinco forem do mesmo naipe, a combinação é outra, ainda mais forte: o straight flush.', ['Não precisa: sequência é só sobre os valores.', null, 'Não há regra sobre os naipes das primeiras cartas.', 'A regra é a mesma em qualquer formato.']);
  q('z3_4#0', 'Flush são cinco cartas do mesmo naipe, de quaisquer valores.', [null, 'Cinco valores seguidos é a sequência.', 'Trinca mais par é o full house.', 'Quatro cartas iguais é a quadra.']);
  q('z3_4#1', 'O full house (trinca + par) vence o flush, porque é mais raro.', ['O flush é mais comum que o full house, por isso vale menos.', null, 'São combinações diferentes: o full house está acima.', 'A ordem das combinações é fixa.']);
  q('z3_4#2', 'O royal flush (10-J-Q-K-A do mesmo naipe) é a combinação mais forte: é o straight flush mais alto possível.', ['A quadra perde para o straight flush e para o royal flush.', null, 'O full house está abaixo da quadra e do straight flush.', 'Um flush de ases ainda é só flush, abaixo do full house.']);
  q('z3_5#0', 'Na escada das combinações, a sequência fica acima de dois pares (e também acima da trinca).', [null, 'Dois pares estão abaixo da trinca e da sequência.', 'São categorias diferentes, então não há empate.', 'A ordem das categorias é fixa.']);
  q('z3_5#1', 'Uma combinação vale mais quando é mais rara. Por isso a ordem não é arbitrária: quanto mais difícil de formar, mais alta.', [null, 'A aparência das cartas não importa.', 'Há um motivo claro: a raridade.', 'Toda combinação usa 5 cartas.']);
  q('z3_5#2', 'Se os dois jogos de 5 cartas têm exatamente os mesmos valores, é empate e o pote é dividido. O naipe nunca desempata.', [null, 'Copas não vale mais: naipes não desempatam.', 'A ordem das apostas não decide o pote.', 'Não se joga de novo: o pote é dividido.']);
  q('z3!ex#0', 'A mesa já dá Q-Q-7-7 para os dois. A quinta carta decide: o seu ás contra o rei dele. Seu jogo: Q-Q-7-7-A; o dele: Q-Q-7-7-K. Você vence pelo kicker.', [null, 'O rei dele é o kicker, mas o seu ás é maior.', 'Os dois pares são iguais, mas os kickers são diferentes.', 'Sempre há um vencedor ou um empate.']);
  q('z3!ex#1', 'A quadra (quatro cartas do mesmo valor) vence o full house, porque é mais rara.', ['O full house é mais comum que a quadra.', null, 'Não são iguais: a quadra está acima.', 'A ordem das combinações é fixa.']);
  q('z3!ex#2', 'Com 5♥ 4♥ e a mesa A-2-3, você forma A-2-3-4-5: a roda, a sequência mais baixa, em que o ás vale 1.', [null, 'Há só quatro copas (5♥, 4♥, K♥ e 9♥): o flush precisa de cinco.', 'Você tem mais que um par: uma sequência.', 'A sequência é bem melhor que carta alta.']);
  // z4 · Uma rodada
  q('z4_1#0', 'O botão anda um lugar para a esquerda (sentido horário) a cada partida. Assim todos passam por todas as posições.', [null, 'Se ficasse parado, o mesmo jogador teria sempre a melhor posição.', 'O botão não acompanha quem ganhou.', 'Não há sorteio: o movimento é fixo.']);
  q('z4_1#1', 'O botão gira para que todos tenham as mesmas vantagens e desvantagens ao longo do tempo: cada um paga os blinds e cada um joga na melhor posição na sua vez.', [null, 'O objetivo é justiça, não confusão.', 'O movimento é sempre um lugar à esquerda, sem sorteio.', 'O botão só marca a posição; quem distribui as cartas não tem nada a ver com o giro.']);
  q('z4_2#0', 'O small blind é pago pelo primeiro jogador à esquerda do botão. O seguinte paga o big blind.', [null, 'O botão não paga blind (exceto no heads-up).', 'Ganhar a partida anterior não muda nada.', 'Só dois jogadores pagam blinds: o small e o big.']);
  q('z4_2#1', 'Em "1/2", o primeiro número é o small blind e o segundo, o big blind: o big blind é 2.', ['1 é o small blind.', null, '3 é a soma dos dois blinds, não o big blind.', '4 não aparece nos blinds 1/2.']);
  q('z4_2#2', 'Os blinds colocam fichas no pote antes das cartas. Assim sempre há algo a disputar e ninguém pode esperar para sempre por cartas perfeitas.', [null, 'O dealer não recebe os blinds; eles vão para o pote.', 'Quem começa é decidido pela posição.', 'Eles são essenciais para o jogo andar.']);
  q('z4_3#0', 'O flop abre 3 cartas de uma vez. Depois vêm o turn (1 carta) e o river (1 carta).', ['Uma carta sai no turn e outra no river.', 'O flop são três cartas, não duas.', null, 'Cinco é o total da mesa, depois do river.']);
  q('z4_3#1', 'A ordem é pré-flop (só as suas cartas), flop (3 cartas), turn (4ª carta) e river (5ª carta). Se sobrar mais de um jogador, vem o showdown.', [null, 'O turn vem antes do river.', 'O flop vem antes do turn.', 'Essa é a ordem invertida.']);
  q('z4_3#2', 'O showdown é o momento final, em que os jogadores que restaram mostram as cartas e a melhor combinação leva o pote.', [null, 'Não é uma aposta: é a comparação das cartas.', 'A primeira carta da mesa sai no flop.', 'Desistir é sair da partida antes do showdown.']);
  q('z4_4#0', 'Se ninguém apostou nesta etapa, você pode passar (não colocar nada) ou apostar. Não há aposta para pagar, aumentar ou desistir dela.', [null, 'Pagar e aumentar só existem depois que alguém aposta.', 'Desistir sem aposta nenhuma é jogar fora uma chance de graça.', 'Não há o que pagar: ninguém apostou.']);
  q('z4_4#1', 'Pagar (call) é colocar a mesma quantidade que o outro apostou, para continuar na partida.', [null, 'Colocar mais é aumentar (raise).', 'Desistir é sair da partida.', 'Passar sem fichas é o check, que só existe quando ninguém apostou.']);
  q('z4_4#2', 'All-in é apostar todas as suas fichas. No No-Limit você pode fazer isso a qualquer momento.', [null, 'Desistir é o fold.', 'Passar é o check.', 'Ganhar o pote é o resultado, não uma ação.']);
  q('z4_5#0', 'No pré-flop fala primeiro o jogador à esquerda do big blind, porque os blinds já colocaram fichas (é como se já tivessem falado).', [null, 'O small blind fala depois, quando a volta chega nele.', 'O botão fala perto do fim no pré-flop.', 'O big blind é o último a falar no pré-flop.']);
  q('z4_5#1', 'Do flop em diante, o botão fala por último (se ainda estiver na partida). É a melhor posição: ele vê o que todos fizeram antes de decidir.', [null, 'O big blind fala cedo depois do flop.', 'O UTG fala antes do botão.', 'Quem apostou no pré-flop não ganha a última posição: a ordem é sempre pela mesa.']);
  q('z4_6#0', 'Bruno era o small blind: colocou 1 ficha antes das cartas e depois desistiu. Essa ficha ficou no pote.', [null, 'Ele desistiu antes do showdown.', 'Ele saiu antes do flop.', 'As fichas não vão para um jogador: vão para o pote.']);
  q('z4_6#1', 'Quando todos passam, ninguém coloca fichas: o pote fica igual.', [null, 'Para dobrar, alguém teria de apostar e outro pagar.', 'O pote só é dividido em caso de empate no showdown.', 'O pote nunca zera durante a partida.']);
  q('z4_6#2', 'Os dois tinham o mesmo par. A carta seguinte de cada um (o kicker) decidiu: ás da Ana contra dama do adversário.', [null, 'A ordem das apostas não decide o showdown.', 'A posição não decide o showdown; só as cartas.', 'A quantidade de fichas não decide o showdown.']);
  q('z4!ex#0', 'Sem aposta anterior nesta etapa, você pode passar ou apostar.', [null, 'Pagar e aumentar exigem uma aposta antes.', 'Desistir sem aposta é jogar fora o pote de graça.', 'Não há nada para pagar.']);
  q('z4!ex#1', 'Até 4 rodadas de apostas: pré-flop, flop, turn e river. Pode haver menos se todos desistirem antes.', [null, 'Há uma rodada em cada etapa, não só uma.', 'São quatro etapas com apostas.', 'São no máximo quatro.']);
  q('z4!ex#2', 'Em "5/10", o primeiro número é o small blind (5) e o segundo, o big blind (10).', [null, '10 é o big blind.', '15 é a soma dos blinds.', '1 não aparece nos blinds 5/10.']);
  // z5 · Primeiras decisões
  q('z5_1#0', 'Jogadores experientes desistem antes do flop em 7 ou 8 de cada 10 partidas. Escolher quando entrar é a base do jogo vencedor.', ['Desistir só 1 vez em 10 é jogar quase todas as mãos: é o que fazem os jogadores que perdem.', null, 'Nunca desistir significa jogar mãos fracas demais.', 'Desistir sempre faz você perder os blinds sem nunca ganhar.']);
  q('z5_1#1', 'Desistir sempre faz você perder os blinds a cada volta, sem nunca ganhar um pote. É preciso escolher as partidas boas e jogá-las.', [null, 'Não é proibido; só dá prejuízo.', 'Não há azar envolvido: é conta.', 'O motivo é claro: os blinds custam fichas.']);
  q('z5_2#0', 'O par de ases (A♠A♥) é a melhor mão inicial do Texas Hold\'em: já começa com um par do valor mais alto.', [null, 'K♦Q♦ é boa, mas fica atrás de um par de ases na maioria das vezes.', '9♣8♣ é jogável em situações certas, mas é bem mais fraca.', '7♠2♦ é considerada a pior mão inicial.']);
  q('z5_2#1', '7-2 de naipes diferentes tem cartas baixas, distantes demais para formar sequência juntas e de naipes diferentes, sem chance de flush juntas: as duas não trabalham juntas.', [null, 'Não existe carta de azar: o problema é matemático.', 'O 2 sozinho não é o problema; é o conjunto de cartas baixas, distantes e de naipes diferentes.', 'É, sim, a mão mais fraca.']);
  q('z5_2#2', 'Ter duas cartas do mesmo naipe é um bônus pequeno: aumenta um pouco a chance de flush, mas não transforma uma mão fraca em forte.', [null, 'Nada garante vitória; o flush só se completa poucas vezes.', 'Faz alguma diferença, mas pequena.', 'Não há nada proibido nisso.']);
  q('z5_3#0', 'Uma boa decisão é aquela que, repetida muitas vezes, ganha fichas no total. Ela pode perder numa partida e continuar boa.', [null, 'Nenhuma decisão ganha sempre; a sorte de cada partida varia.', 'Ter dado certo uma vez não prova que a decisão é boa.', 'Rapidez não mede qualidade.']);
  q('z5_3#1', 'Se a aposta era vantajosa, a decisão foi boa. Perder foi o azar daquela partida; repetida muitas vezes, ela dá lucro.', [null, 'Julgar pelo resultado faz você abandonar boas decisões.', 'Dá para avaliar: a aposta era vantajosa pelas contas.', 'A qualidade da decisão é o que mais importa no longo prazo.']);
  q('z5_4#0', 'Jogue só com um valor que você pode perder sem afetar a sua vida. Dinheiro de contas, de reserva ou emprestado nunca.', [null, 'Dinheiro do aluguel é necessário para viver: nunca deve ir para o jogo.', 'Dinheiro emprestado transforma perdas normais em dívidas.', 'Não é qualquer um: só o que você pode perder com tranquilidade.']);
  q('z5_4#1', 'Jogar para recuperar o que perdeu é um sinal clássico de alerta: a decisão passa a ser emocional, e as perdas costumam aumentar.', [null, 'Estudar antes de jogar é um bom hábito.', 'Definir um limite é uma proteção, não um alerta.', 'Fazer pausas é saudável.']);
  q('z5!ex#0', '7♣2♦ é a mais fraca: cartas baixas, distantes e de naipes diferentes.', [null, 'A♥K♥ é uma das melhores mãos iniciais.', 'Q♠Q♦ é um par alto, mão forte.', 'J♣T♣ é próxima e do mesmo naipe: bem jogável.']);
  q('z5!ex#1', 'Eles desistem muito porque continuar com cartas fracas custa fichas no longo prazo. Jogar menos mãos, e melhores, é o que dá lucro.', [null, 'Não é medo: é conta.', 'Não existe regra que obrigue a desistir.', 'Não tem nada de superstição.']);
  q('z5!ex#2', 'Mantenha a decisão: se ela foi boa, perder foi a sorte daquela partida. Mudar por causa de um resultado faz você trocar o certo pelo errado.', [null, 'Mudar tudo por um resultado é reagir à sorte, não à qualidade.', 'Parar de jogar por uma perda normal não faz sentido.', 'Jogar mais para recuperar é perseguir perdas, um sinal de alerta.']);
})(typeof window !== 'undefined' ? window : globalThis);
